language: python
sudo: enabled
python:
    - "3.8"
env:
    global:
     - TRAVIS=true
# command to install dependencies
install:
    - pip install -r requirements.txt
    
#script:
#    python manage.py test
